engines:
  rubocop:
    enabled: true
    #checks:
    #  Rubocop/Metrics/ClassLength:
    #    enabled: false
  shellcheck:
    enabled: true
  duplication:
    enabled: false
    config:
      languages:
      - ruby:
      - javascript:
ratings:
  paths:
#  - "**.sh"
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
  - spec/**/*
  - spec2018/**/*
exclude_paths:
# - spec/**/*
- "**/vendor/**/*"
